### PR TITLE
Added CMAKE_BUILD_WITH_INSTALL_RPATH TRUE to CMakeLists.txt to avoid …

### PR DESCRIPTION
**Pull request by estewart08**
…changing RPATH on install

### CODE REVIEW

**Comment by estewart08** [comment]
Fixed issue: https://github.com/RadeonOpenCompute/atmi/issues/11

**Comment by ashwinma** [comment]
Thanks for the PR. Can you explain to me what the implications are with the PR where we force install RPATH during build? Just wanted to understand all the consequences, that’s all.

I was seeing ROCr and they explicitly have an install-only RPATH (CMAKE_INSTALL_RPATH) targeting $ORIGIN.
https://github.com/RadeonOpenCompute/ROCR-Runtime/blob/3eed1b46fcf4e7e3c256b0421616fb9c365dbebd/src/CMakeLists.txt#L114

Pros and cons of the two approaches?

**Comment by haampie** [comment]
I don't see how this fix is related to the issue. No variables related to INSTALL_RPATH are defined in the CMakeLists.txt files?

**Comment by estewart08** [comment]
I posited that the rpath automatically chosen by cmake during the build was causing some issues. I was trying to avoid the re-linking on ```make install``` by using the install RPATH (CMAKE_BUILD_WITH_INSTALL_RPATH TRUE) during the build so cmake did not have to bother with the build tree rpath. Why that was causing issues I am not exactly sure. 

I did not have gentoo to reproduce this issue and test the fix, but the user said the security error went away. 

Ashwin, your additional commit should be fine.

**Pull request merged**
